
name: my_server
ships:
  # Ships definitions (see below)
  media:   {ip: 127.0.0.1, docker_port: 5555}

services:
  statbot:
   image: hamiltont/statbot
   instances:
     statbot: 
       ship: my_server
       ports: {api: 3001}
       lifecycle: 
         running: [{type: tcp, port: api}]
       volumes:
         /statbot/data:              /lxc/statbot/data
         /statbot/src/config:        /lxc/statbot/config
